'use strict';
const http=require('http');
const crypto=require('crypto');
const {Pool}=require('pg');
const webpush=require('web-push');
const PORT=Number(process.env.PORT||3000);
const BEARER=String(process.env.PUSH_ADAPTER_BEARER||process.env.AUTH_SECRET||'');
const VAPID_PUBLIC_KEY=String(process.env.VAPID_PUBLIC_KEY||'');
const VAPID_PRIVATE_KEY=String(process.env.VAPID_PRIVATE_KEY||'');
const VAPID_SUBJECT=String(process.env.VAPID_SUBJECT||'mailto:support@minjaz.app');
const pool=new Pool({host:process.env.PGHOST,port:Number(process.env.PGPORT||5432),user:process.env.PGUSER,password:process.env.PGPASSWORD,database:process.env.PGDATABASE,max:8,idleTimeoutMillis:30000});
function configured(){return BEARER.length>=24&&VAPID_PUBLIC_KEY.length>40&&VAPID_PRIVATE_KEY.length>20}
if(VAPID_PUBLIC_KEY&&VAPID_PRIVATE_KEY)webpush.setVapidDetails(VAPID_SUBJECT,VAPID_PUBLIC_KEY,VAPID_PRIVATE_KEY);
function secureEqual(a,b){const aa=Buffer.from(String(a||'')),bb=Buffer.from(String(b||''));return aa.length===bb.length&&aa.length>0&&crypto.timingSafeEqual(aa,bb)}
function authorized(req){const h=String(req.headers.authorization||'');return h.startsWith('Bearer ')&&secureEqual(h.slice(7).trim(),BEARER)}
function reply(res,status,obj){const out=Buffer.from(JSON.stringify(obj));res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':out.length,'cache-control':'no-store','x-content-type-options':'nosniff'});res.end(out)}
async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>262144)throw Object.assign(new Error('too_large'),{status:413});chunks.push(chunk)}if(!chunks.length)return {};try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch(_){throw Object.assign(new Error('invalid_json'),{status:400})}}
function validEndpoint(v){try{const u=new URL(String(v||''));return u.protocol==='https:'&&String(v).length<=2048}catch(_){return false}}
async function ensureSchema(){await pool.query(`create table if not exists push_subscriptions(id bigserial primary key,user_id bigint not null references users(id) on delete cascade,endpoint text not null unique,p256dh text not null,auth_key text not null,expiration_time bigint,user_agent text,failure_count int not null default 0,last_success_at timestamptz,last_failure_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now())`);await pool.query('create index if not exists idx_push_subscriptions_user on push_subscriptions(user_id,updated_at desc)')}
async function registerSubscription(payload){const uid=Number(payload.user_id||0),sub=payload.subscription||{},keys=sub.keys||{},endpoint=String(sub.endpoint||''),p256dh=String(keys.p256dh||''),auth=String(keys.auth||'');if(!Number.isInteger(uid)||uid<=0||!validEndpoint(endpoint)||!p256dh||!auth||p256dh.length>512||auth.length>512)throw Object.assign(new Error('invalid_subscription'),{status:400});await pool.query(`insert into push_subscriptions(user_id,endpoint,p256dh,auth_key,expiration_time,user_agent,failure_count,updated_at) values($1,$2,$3,$4,$5,$6,0,now()) on conflict(endpoint) do update set user_id=excluded.user_id,p256dh=excluded.p256dh,auth_key=excluded.auth_key,expiration_time=excluded.expiration_time,user_agent=excluded.user_agent,failure_count=0,updated_at=now()`,[uid,endpoint,p256dh,auth,sub.expirationTime?Number(sub.expirationTime):null,String(payload.user_agent||'').slice(0,500)||null]);return {ok:true}}
async function deleteSubscription(payload){const uid=Number(payload.user_id||0),endpoint=String(payload.endpoint||'');if(!Number.isInteger(uid)||uid<=0||!validEndpoint(endpoint))throw Object.assign(new Error('invalid_subscription'),{status:400});const r=await pool.query('delete from push_subscriptions where user_id=$1 and endpoint=$2',[uid,endpoint]);return {ok:true,deleted:r.rowCount}}
async function sendToUser(payload){const uid=Number(payload.user_id||0);if(!Number.isInteger(uid)||uid<=0)throw Object.assign(new Error('invalid_user'),{status:400});if(!configured())throw Object.assign(new Error('push_not_configured'),{status:503});const rows=(await pool.query('select id,endpoint,p256dh,auth_key from push_subscriptions where user_id=$1 order by updated_at desc limit 20',[uid])).rows;const message=JSON.stringify({title:String(payload.title||'مِنجاز').slice(0,180),body:String(payload.body||'').slice(0,1200),url:String(payload.url||'/#notifications').slice(0,500),tag:'minjaz-'+String(payload.kind||'general').slice(0,60),kind:String(payload.kind||'general').slice(0,80),order_id:payload.order_id||null,task_id:payload.task_id||null});let sent=0,removed=0,failed=0;for(const row of rows){try{await webpush.sendNotification({endpoint:row.endpoint,keys:{p256dh:row.p256dh,auth:row.auth_key}},message,{TTL:180,urgency:'normal'});sent++;await pool.query('update push_subscriptions set failure_count=0,last_success_at=now(),updated_at=now() where id=$1',[row.id])}catch(err){const status=Number(err&&err.statusCode||0);if(status===404||status===410){removed++;await pool.query('delete from push_subscriptions where id=$1',[row.id])}else{failed++;await pool.query('update push_subscriptions set failure_count=failure_count+1,last_failure_at=now(),updated_at=now() where id=$1',[row.id])}}}return {ok:true,subscriptions:rows.length,sent,failed,removed}}
const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(req.method==='GET'&&url.pathname==='/health'){let database=false;try{await pool.query('select 1');database=true}catch(_){}return reply(res,database&&configured()?200:503,{ok:database&&configured(),database,push_configured:configured()})}if(!authorized(req))return reply(res,401,{error:'unauthorized'});if(req.method==='GET'&&url.pathname==='/v1/config')return reply(res,200,{ok:true,public_key:VAPID_PUBLIC_KEY});if(req.method==='POST'&&url.pathname==='/v1/subscriptions')return reply(res,201,await registerSubscription(await body(req)));if(req.method==='DELETE'&&url.pathname==='/v1/subscriptions')return reply(res,200,await deleteSubscription(await body(req)));if(req.method==='POST'&&url.pathname==='/v1/send')return reply(res,200,await sendToUser(await body(req)));return reply(res,404,{error:'not_found'})}catch(err){const status=Number(err&&err.status||0)||500;console.error('PUSH_ERR',err&&err.message||err);return reply(res,status,{error:status>=500?'internal_error':String(err.message||'invalid_request')})}});
ensureSchema().then(()=>server.listen(PORT,'0.0.0.0',()=>console.log('MINJAZ_PUSH_READY',PORT))).catch(err=>{console.error('PUSH_BOOT_ERR',err);process.exit(1)});
