plugins {
    id 'com.android.application'
}

android {
    namespace 'sa.minjaz.preview'
    compileSdk 36

    defaultConfig {
        applicationId "sa.minjaz.preview"
        minSdk 24
        targetSdk 36
        versionCode 6
        versionName "0.6-release-prep"
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }

        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
