plugins {
    id 'com.android.application'
}

android {
    namespace 'sa.minjaz.preview'
    compileSdk 36

    defaultConfig {
        minSdk 24
        targetSdk 36
    }

    flavorDimensions += "distribution"
    productFlavors {
        preview {
            dimension "distribution"
            applicationId "sa.minjaz.preview"
            versionCode 10
            versionName "0.10-android-stability"
        }
        production {
            dimension "distribution"
            applicationId "sa.minjaz.app"
            versionCode 11
            versionName "1.0.0-rc1"
        }
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }

        release {
            debuggable false
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
